version: "3.8"
services:
  heimdall-wrapper:
    image: php:8.2-apache:latest
    container_name: heimdall-wrapper
    ports:
      - ${HW_PORT}:80
    volumes:
      - ./app:/html/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf